image: 
  repository: eu.gcr.io/bluelabs-container-registry/data-lyft-flink-operator
  tag:
  pullPolicy: Always
ingress:
  suffix: flinkingress
debug: false
resources:
  # limits:
  #   cpu: 2
  #   memory: 2Gi
  requests:
    cpu: 1
    memory: 512Mi

retry:
  baseBackoffDuration: 20s
  maxBackoffDuration: 60s
  maxErrDuration: 5m

limitNamespace: data
# nodeAffinityDomain: data