kind: ConfigMap
apiVersion: v1
metadata:
  name: flink-operator-config
  namespace: data
data:
  # this will need to be templatized
  config: |-
    operator:
      ingressUrlFormat: "{{`{{$jobCluster}}`}}.{{ .Values.ingress.suffix | default `flinkingress` }}"
      baseBackoffDuration: {{ .Values.retry.baseBackoffDuration | default `20s` }}
      maxBackoffDuration: {{ .Values.retry.maxBackoffDuration | default `60s` }}
      maxErrDuration: {{ .Values.retry.maxErrDuration | default `5m` }}
      limitNamespace: {{ .Values.limitNamespace | default `data` }}
    logger:
      level: 4
